import type { AppState, Book, Poem, User } from "./types";
import { DEFAULT_POEM_STYLE, getThemeDefaultText } from "./poem-style";

const now = new Date();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86400000).toISOString();

export const DEMO_USER_ID = "user-demo";

export const DEMO_USERS: User[] = [
  {
    id: DEMO_USER_ID,
    username: "ruimendes",
    displayName: "Rui Mendes",
    bio: "Poeta amador. Chuva, cidade e silêncio.",
    avatarColor: "#C4956A",
    styleTags: ["cidade", "melancolia"],
    pinnedPoemIds: [],
    createdAt: daysAgo(90),
  },
  {
    id: "user-ines",
    username: "inesmar",
    displayName: "Inês Mar",
    bio: "Poeta do atlântico. Sal, luar e versos elegantes.",
    avatarColor: "#2E86AB",
    styleTags: ["mar", "elegante", "haiku"],
    pinnedPoemIds: ["poem-ines-1"],
    createdAt: daysAgo(110),
  },
  {
    id: "user-tomas",
    username: "tomasverso",
    displayName: "Tomás Verso",
    bio: "Versos urbanos. Metro, neon e silêncio de elevador.",
    avatarColor: "#4A4E69",
    styleTags: ["cidade", "minimalista"],
    pinnedPoemIds: ["poem-tomas-2"],
    createdAt: daysAgo(85),
  },
  {
    id: "user-lua",
    username: "luaferreira",
    displayName: "Lua Ferreira",
    bio: "Romance em prosa curta. Janelas, mãos e dezembro.",
    avatarColor: "#C9184A",
    styleTags: ["amor", "íntimo"],
    pinnedPoemIds: ["poem-lua-1"],
    createdAt: daysAgo(70),
  },
  {
    id: "user-ze",
    username: "zepassaro",
    displayName: "Zé Pássaro",
    bio: "Campo e rio. Poesia livre com cheiro a pinho.",
    avatarColor: "#2D6A4F",
    styleTags: ["natureza", "rural"],
    pinnedPoemIds: [],
    createdAt: daysAgo(55),
  },
];

const SEED_POEMS: Poem[] = [
  // Inês Mar — elegante / clássica / moderna
  {
    id: "poem-ines-1",
    authorId: "user-ines",
    title: "Maré Baixa",
    body: '<p style="text-align: center">A maré recua devagar<br>como quem não quer ir embora.<br>Deixa conchas no calçado<br>e promessas na areia molhada.</p>',
    font: "elegant",
    theme: "ocean",
    textColor: "#0c4a6e",
    fontSize: "lg",
    privacy: "public",
    hashtags: ["mar", "atlântico"],
    applauseCount: 62,
    snapCount: 28,
    commentCount: 3,
    viewCount: 418,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "poem-ines-2",
    authorId: "user-ines",
    title: "Farol Apagado",
    body: "O farol dormiu antes da tempestade.\nAlguém contou as ondas de memória\naté perder a conta\n— e ficou só o escuro\na respirar no cais.",
    font: "classic",
    theme: "midnight",
    textColor: getThemeDefaultText("midnight"),
    fontSize: "md",
    privacy: "public",
    hashtags: ["noite", "mar"],
    applauseCount: 41,
    snapCount: 19,
    commentCount: 1,
    viewCount: 276,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "poem-ines-3",
    authorId: "user-ines",
    title: "Sal na Pele",
    body: '<p>Verão curto.<br>Vontade longa.<br>O sal fica quando o corpo já foi embora.</p>',
    font: "sans",
    theme: "slate",
    textColor: "#334155",
    fontSize: "sm",
    privacy: "public",
    hashtags: ["verão", "corpo"],
    applauseCount: 88,
    snapCount: 44,
    commentCount: 2,
    viewCount: 531,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  // Tomás Verso — máquina / sans
  {
    id: "poem-tomas-1",
    authorId: "user-tomas",
    title: "Elevador",
    body: "Sobe.\nPara.\nDesce.\nNinguém olha.\nTodos chegam\ntarde demais\npara alguma coisa.",
    font: "typewriter",
    theme: "dark",
    textColor: getThemeDefaultText("dark"),
    fontSize: "md",
    privacy: "public",
    hashtags: ["cidade", "metro"],
    applauseCount: 95,
    snapCount: 51,
    commentCount: 4,
    viewCount: 612,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "poem-tomas-2",
    authorId: "user-tomas",
    title: "Último Autocarro",
    body: '<p style="text-align: right">Luzes de sodium.<br>Cartão sem saldo.<br>Cidade a fechar os olhos.<br>Eu ainda acordado<br>com versos no bolso.</p>',
    font: "typewriter",
    theme: "wine",
    textColor: "#fecdd3",
    fontSize: "lg",
    privacy: "public",
    hashtags: ["noite", "lisboa"],
    applauseCount: 73,
    snapCount: 36,
    commentCount: 2,
    viewCount: 489,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(4),
  },
  {
    id: "poem-tomas-3",
    authorId: "user-tomas",
    title: "Neon",
    body: '<p style="text-align: center"><span style="color: #be123c">P</span>isca.<br><span style="color: #cbd5e1">Apaga.</span><br>Recomeça.<br>Como tudo o que insistimos em amar.</p>',
    font: "sans",
    theme: "midnight",
    textColor: "#e2e8f0",
    fontSize: "xl",
    privacy: "public",
    hashtags: ["neon", "cidade"],
    applauseCount: 112,
    snapCount: 58,
    commentCount: 6,
    viewCount: 743,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  // Lua Ferreira — clássica / elegante
  {
    id: "poem-lua-1",
    authorId: "user-lua",
    title: "Dezembro",
    body: "Em dezembro até o silêncio treme.\nGuardo o teu nome\nentre o cachecol e a respiração,\ncomo quem esconde fogo\nnuma mão pequena.",
    font: "classic",
    theme: "rose",
    textColor: "#881337",
    fontSize: "lg",
    privacy: "public",
    hashtags: ["amor", "inverno"],
    applauseCount: 156,
    snapCount: 72,
    commentCount: 9,
    viewCount: 924,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "poem-lua-2",
    authorId: "user-lua",
    title: "Mãos",
    body: '<p style="text-align: center"><em>As tuas mãos sabiam<br>perguntar sem pressa.<br>As minhas aprenderam<br>a ficar.</em></p>',
    font: "elegant",
    theme: "cream",
    textColor: "#92400e",
    fontSize: "md",
    privacy: "public",
    hashtags: ["mãos", "ternura"],
    applauseCount: 98,
    snapCount: 49,
    commentCount: 5,
    viewCount: 567,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: "poem-lua-3",
    authorId: "user-lua",
    title: "Antes do Adeus",
    body: "Não digas nada.\nDeixa a frase inteira\nno copo meio cheio\ne no botão do casaco\nque ainda não abro.",
    font: "classic",
    theme: "wine",
    textColor: "#fecdd3",
    fontSize: "md",
    privacy: "followers",
    hashtags: ["adeus", "silêncio"],
    applauseCount: 34,
    snapCount: 17,
    commentCount: 1,
    viewCount: 128,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  // Zé Pássaro — sans / clássica / máquina
  {
    id: "poem-ze-1",
    authorId: "user-ze",
    title: "Trilho",
    body: "O trilho não pergunta\npara onde vais.\nSó abre caminho\nentre pinheiros\n e o cheiro a terra\n depois da chuva.",
    font: "sans",
    theme: "forest",
    textColor: "#14532d",
    fontSize: "md",
    privacy: "public",
    hashtags: ["montanha", "trilho"],
    applauseCount: 54,
    snapCount: 27,
    commentCount: 2,
    viewCount: 341,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "poem-ze-2",
    authorId: "user-ze",
    title: "Rio Lento",
    body: '<p style="text-align: center">Água que nunca tem pressa.<br>Leva folhas, leva nomes,<br>devolve estrelas ao céu<br>quando anoitece.</p>',
    font: "classic",
    theme: "ocean",
    textColor: "#1e3a5f",
    fontSize: "lg",
    privacy: "public",
    hashtags: ["rio", "natureza"],
    applauseCount: 67,
    snapCount: 31,
    commentCount: 3,
    viewCount: 402,
    createdAt: daysAgo(9),
    updatedAt: daysAgo(9),
  },
  {
    id: "poem-ze-3",
    authorId: "user-ze",
    title: "Campo",
    body: "campo aberto\nviento\nsem ponto final",
    font: "typewriter",
    theme: "parchment",
    textColor: "#44403c",
    fontSize: "sm",
    privacy: "public",
    hashtags: ["campo", "liberdade"],
    applauseCount: 39,
    snapCount: 18,
    commentCount: 1,
    viewCount: 215,
    createdAt: daysAgo(11),
    updatedAt: daysAgo(11),
  },
];

const SEED_BOOKS: Book[] = [
  {
    id: "book-ines",
    authorId: "user-ines",
    title: "Cartas à Orla",
    description: "Poemas escritos entre marés — do atlântico para quem escuta.",
    slug: "cartas-a-orla",
    poemIds: ["poem-ines-1", "poem-ines-2", "poem-ines-3"],
    sections: [
      {
        id: "sec-ines-1",
        bookId: "book-ines",
        type: "dedication",
        body: "Para quem me ensinou a ouvir o mar antes de o ver.",
        placement: "front",
        position: 0,
        createdAt: daysAgo(10),
      },
      {
        id: "sec-ines-2",
        bookId: "book-ines",
        type: "epigraph",
        body: "«A maré escreve e apaga — nós ficamos com o sal.»",
        placement: "front",
        position: 1,
        createdAt: daysAgo(10),
      },
    ],
    isPublic: true,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: "book-tomas",
    authorId: "user-tomas",
    title: "Cidade Vertical",
    description: "Versos de elevador, autocarro e luzes que não dormem.",
    slug: "cidade-vertical",
    poemIds: ["poem-tomas-1", "poem-tomas-2", "poem-tomas-3"],
    sections: [
      {
        id: "sec-tomas-1",
        bookId: "book-tomas",
        type: "epigraph",
        body: "«Ninguém chega tarde para o poema — só para si.»",
        placement: "front",
        position: 0,
        createdAt: daysAgo(8),
      },
    ],
    isPublic: true,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: "book-lua",
    authorId: "user-lua",
    title: "Quarto com Janela",
    description: "Poemas íntimos sobre amor, ausência e o inverno dentro de nós.",
    slug: "quarto-com-janela",
    poemIds: ["poem-lua-1", "poem-lua-2", "poem-lua-3"],
    sections: [
      {
        id: "sec-lua-1",
        bookId: "book-lua",
        type: "dedication",
        body: "A quem deixou a luz acesa quando eu não sabia voltar.",
        placement: "front",
        position: 0,
        createdAt: daysAgo(6),
      },
    ],
    isPublic: true,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },
  {
    id: "book-ze",
    authorId: "user-ze",
    title: "Debaixo do Céu",
    description: "Trilhos, rios e campos — poesia com cheiro a pinho.",
    slug: "debaixo-do-ceu",
    poemIds: ["poem-ze-1", "poem-ze-2", "poem-ze-3"],
    sections: [
      {
        id: "sec-ze-1",
        bookId: "book-ze",
        type: "preface",
        title: "Nota",
        body: "Estes poemas nasceram caminhando. Leia-os devagar, como se fosse trilho.",
        placement: "front",
        position: 0,
        createdAt: daysAgo(12),
      },
    ],
    isPublic: true,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    id: "book-demo",
    authorId: DEMO_USER_ID,
    title: "Primeiras Linhas",
    description: "Uma coleção inicial de versos e rascunhos.",
    slug: "primeiras-linhas",
    poemIds: [],
    sections: [],
    isPublic: false,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
];

export const SEED_STATE: Omit<AppState, "hydrated" | "currentUserId" | "cloudEnabled" | "lastCloudSyncAt"> = {
  users: DEMO_USERS,
  poems: SEED_POEMS,
  drafts: [],
  follows: [
    { followerId: DEMO_USER_ID, followingId: "user-ines", createdAt: daysAgo(30) },
    { followerId: DEMO_USER_ID, followingId: "user-tomas", createdAt: daysAgo(28) },
    { followerId: DEMO_USER_ID, followingId: "user-lua", createdAt: daysAgo(25) },
    { followerId: DEMO_USER_ID, followingId: "user-ze", createdAt: daysAgo(20) },
    { followerId: "user-ines", followingId: DEMO_USER_ID, createdAt: daysAgo(15) },
    { followerId: "user-lua", followingId: "user-ines", createdAt: daysAgo(10) },
    { followerId: "user-tomas", followingId: "user-lua", createdAt: daysAgo(8) },
  ],
  reactions: [
    { id: "react-1", userId: DEMO_USER_ID, poemId: "poem-ines-1", type: "applause", createdAt: daysAgo(1) },
    { id: "react-2", userId: DEMO_USER_ID, poemId: "poem-lua-1", type: "snap", createdAt: daysAgo(2) },
    { id: "react-3", userId: DEMO_USER_ID, poemId: "poem-tomas-3", type: "applause", createdAt: daysAgo(1) },
    { id: "react-4", userId: "user-lua", poemId: "poem-ines-2", type: "snap", createdAt: daysAgo(3) },
  ],
  comments: [
    {
      id: "comment-1",
      poemId: "poem-ines-1",
      authorId: "user-tomas",
      body: "A imagem da maré a recuar ficou comigo o dia inteiro.",
      createdAt: daysAgo(1),
    },
    {
      id: "comment-2",
      poemId: "poem-ines-1",
      authorId: DEMO_USER_ID,
      body: "O alinhamento ao centro funciona muito bem aqui.",
      createdAt: daysAgo(0),
    },
    {
      id: "comment-3",
      poemId: "poem-lua-1",
      authorId: "user-ines",
      body: "Dezembro nunca me pareceu tão gentil.",
      createdAt: daysAgo(2),
    },
  ],
  bookmarkCollections: [
    { id: "col-1", userId: DEMO_USER_ID, name: "Favoritos", createdAt: daysAgo(10) },
    { id: "col-2", userId: DEMO_USER_ID, name: "Para reler", createdAt: daysAgo(5) },
  ],
  bookmarks: [
    { id: "bm-1", collectionId: "col-1", poemId: "poem-lua-1", createdAt: daysAgo(2) },
    { id: "bm-2", collectionId: "col-1", poemId: "poem-tomas-3", createdAt: daysAgo(1) },
  ],
  conversations: [
    { id: "conv-1", participantIds: [DEMO_USER_ID, "user-ines"], updatedAt: daysAgo(0) },
  ],
  messages: [
    {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "user-ines",
      body: "Olá! Gostaste do poema sobre a maré?",
      createdAt: daysAgo(1),
      read: true,
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      senderId: DEMO_USER_ID,
      body: "Sim, ficou lindo. Queres fazer um poema colaborativo?",
      createdAt: daysAgo(0),
      read: true,
    },
  ],
  collaborativePoems: [
    {
      id: "collab-1",
      title: "Dois na varanda",
      participantIds: [DEMO_USER_ID, "user-ines"],
      verses: [
        { authorId: DEMO_USER_ID, text: "A varanda olha o rio", order: 0 },
        { authorId: "user-ines", text: "como quem espera uma resposta", order: 1 },
        { authorId: DEMO_USER_ID, text: "que nunca veio por barco", order: 2 },
      ],
      status: "active",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(0),
    },
  ],
  challenges: [
    {
      id: "challenge-1",
      title: "Desafio da Semana",
      prompt: "Escreve um poema sobre a chuva em 4 linhas.",
      hashtag: "desafiochuva",
      startsAt: daysAgo(2),
      endsAt: daysAgo(-5),
    },
    {
      id: "challenge-2",
      title: "Próximo Desafio",
      prompt: "Um poema sobre silêncio — máximo 6 versos.",
      hashtag: "desafiosilencio",
      startsAt: daysAgo(-5),
      endsAt: daysAgo(-12),
    },
  ],
  books: SEED_BOOKS,
  notifications: [],
  notificationMutes: [],
  draftVersions: [],
  offlineQueue: [],
  trendingHashtags: [],
  isOnline: true,
};
